# Generated by Django 3.2.12 on 2023-12-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('test1', models.CharField(max_length=255)),
                ('test2', models.CharField(max_length=255)),
                ('test3', models.CharField(max_length=255)),
                ('test4', models.CharField(max_length=255)),
                ('test5', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packages')),
            ],
        ),
    ]
