# Generated by Django 3.2.12 on 2024-01-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subblog',
        ),
    ]
