# Generated by Django 3.2.12 on 2024-01-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sub_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subpackage',
        ),
    ]
